### ISSUE TITLE
No UDP requests

### ISSUE THREAD

**Issue by tobiaslins** [jghaanstra/com.robot.xiaomi-mi#1]
Hey,

I was wondering if I need bluestacks (bluestacks is not supported yet on mac os sierra) ? Should it not be possible to just sniff the requests from my phone directly?

I can't find packages to my Mi robot.. :(
Could it be because of that?

I also tried to use a mitmproxy, but i can just see outgoing requests to https://api.io.mi.com/app/home/rpc/******

**Comment by jghaanstra** [comment]
I had the same experience when trying to sniff the packets directly from my phone using Fiddler and Charles as MITM proxy. I'm not sure why but I was not able to see the local UPD requests needed to retrieve the right UDP packets but only saw the cloud requests that way. Your best bet is to find an alternative to BlueStacks I guess.
