### ISSUE TITLE
does appium supports the windows app which is developed in QT

### ISSUE THREAD

**Issue by naveen2415** [jghaanstra/com.robot.xiaomi-mi#3]
i'm facing no such element exception, even i have provided the valid element property(i.e. name). Now my question is does appium supports the windows app which is developed in **QT**

**Comment by jghaanstra** [comment]
I'm assuming you accidently posted your issue in the wrong repository as your question seems unrelated to this repo (which holds a node.js app for the domotica controller called Homey). So I'm closing this issue.
