### ISSUE TITLE
Homebridge + Mi Robot Plugin

### ISSUE THREAD

**Issue by Ant1q** [jghaanstra/com.robot.xiaomi-mi#4]
Hello! I am following instrusctions in readme - catch start and stop packet's, test them in the PacketSender, but when i use HomeKit to start vacuum cleaner - nothing happens, homebridge shows 
```
[2017-02-11 15:24:51] [Vacuum Cleaner] start robo
[2017-02-11 15:24:53] [Vacuum Cleaner] stop robo
```
I have already check the ip, hex-packets, try add port to IP and change index.js direct to my ip and hex-packet. What am I doing wrong?

**Comment by tobiaslins** [comment]
@Ant1q 
Which plugin are you using? this one is not for homebridge i guess

**Comment by Ant1q** [comment]
From npmjs.com for homebridge, link in description for this project, so i asked here. I have already resolved my problem with another plugin.

**Comment by tobiaslins** [comment]
@Ant1q probably you used mine - if yes I could help you with homebridge ([homebridge-mi-robot-vacuum](https://github.com/tobiaslins/homebridge-mi-robot-vacuum)

**Comment by jghaanstra** [comment]
Closing this as it's not related to this repo and the problem seems to be resolved.
