### ISSUE TITLE
The hex data is the same every time?

### ISSUE THREAD

**Issue by biogerm** [jghaanstra/com.robot.xiaomi-mi#7]
Hi,

I have been trying to reproduce the procedure you have suggested on my Mi power outlet. I don't own a vacuum robot, so what I found from the power outlet are:

1. the hex payload is different every time...
2. most of time the packet is sent from a server outside my LAN...
3. packages are even not with equal size
4. payload sent from my phone directly to the device is bigger than the package from cloud

Does the vacuum robot's package appears in the same way? Can you please describe a little about the package you captured? Maybe it can give me a little help to find out a way to home bridge the outlets. Thanks!

BR
Ryan

**Comment by jghaanstra** [comment]
Hello Ryan,

Cant tell for the Mi Power Outlet but for the Vacuum Cleaner.

1. I assume the HEX payload is always the same. I copied the working payloads when sniffing the traffic from my Vacuum Cleaner en reuse them now from a script through my LAN.
2. Yes, this also happens with the Vacuum Cleaner, sometimes it works through LAN and sometimes it works through cloud. You have to make sure it's connected through LAN when sniffing.
3. The different commands for the Vacuum Cleaner are indeed not the same size, for instance starting and stopping the vacuum cleaner differ in size.
4. Dont know, when connected through the cloud I could not make any sense from the packages sniffed. See answer 2.

There is not much more to describe what is not already mentioned in the tutorial.

**Comment by biogerm** [comment]
@jghaanstra Thanks for the answers. For No.3 what i observed was that with the same command, the packet sent can be different length. Not randomly, but with a few variants. For example 138 byte, 106 byte and 74 byte. I tried with both the packet sent from a phone and the one from cloud without success. Just wondering, which phone do you use? Is it an Android or iOS?

**Comment by jghaanstra** [comment]
I'm on Android but when I sniffed the packages of my vacuum cleaner I used BlueStacks (Android emulator) on my Windows 10 laptop.

**Comment by biogerm** [comment]
Thanks @jghaanstra I tried blue stacks with mi home app and saw similar result. I could control the switch for a while using packet sender. But after a short while, the switch won't respond. I sniffed more packets and realised that the beginning of the changing part of data payload acts like a counter. It only adds up. I assume that the switch will use this part to decide whether to accept this packet or not. probable to drop time outs since it's unpredictable UDP. I will experiment using an arbitrarily large value and see if it works :)

**Comment by biogerm** [comment]
Nah. It should have some kind of CRC in the end. Changing data won't work.

**Comment by GermanBluefox** [comment]
I don't know what are you doing here, but we can communicate with xiaomi vacuum cleaner. 
Our investigation was based on your repository :)
https://github.com/ioBroker/ioBroker.mihome-vacuum/blob/master/lib/mihomepacket.js

You just need the token.

**Comment by jghaanstra** [comment]
That's good news @GermanBluefox. I'll have a look if this makes things easier for my code as well (which is an app for a domotica controller called Homey allowing it to control the vacuum cleaner).
